spring.application.name=cloudfare
spring.datasource.url=jdbc:mysql://localhost:3306/cloudfare?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Configuration (3MB)
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB

# Email Configuration
spring.mail.host=smtpout.secureserver.net
spring.mail.port=465
spring.mail.username=info@cloudfaretechnologies.com
spring.mail.password=Admin@123#
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.checkserveridentity=true
spring.mail.properties.mail.smtp.ssl.trust=smtpout.secureserver.net
spring.mail.properties.mail.debug=true
